# Generated by Django 3.2.7 on 2021-09-23 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.FloatField()),
                ('weight', models.FloatField()),
                ('type', models.CharField(choices=[('1', 'ARÁBIGO'), ('2', 'ROBUSTA'), ('3', 'LIBÉRICA'), ('4', 'EXCELSA')], max_length=15)),
                ('varieties', models.TextField()),
                ('features', models.PositiveIntegerField()),
                ('state', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
