# Generated by Django 3.2.7 on 2021-09-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='type',
            new_name='coffe_type',
        ),
    ]
