# Generated by Django 3.2.7 on 2021-09-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_type_batch_coffe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='features',
            field=models.TextField(),
        ),
    ]
