# Generated by Django 3.2.7 on 2021-09-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210923_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='history',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
